echo "Hola, mundo desde un script "
echo "Fecha y hora: $(date)"
echo "Usuario: $(whoami)"
echo "Directorio actual: $(pwd)"
echo "Todos los usuarios conectados: $(who)"
echo "Sistema operativo: $(uname -a)"
echo "Versión de Java: $(java -version)"
echo "Versión de Python: $(python --version)"
echo "Versión de Node.js: $(node --version)"
echo "Versión de npm: $(npm --version)"
echo "Versión de Maven: $(mvn --version)"