// Cargar la Shared Library desde la configuración global de Jenkins
@Library('jenkins-shared-library@develop') _

pipeline {
    agent any 
    
    stages {
        stage('Build') {
            steps {
                // Usando la función buildMaven de la shared library
                buildMaven('mi-proyecto')
            }
        }
        
        stage('Test') {
            steps {
                // Usando la función testMaven de la shared library
                testMaven('mi-proyecto')
            }
        }
        
        stage('Deploy') {
            steps {
                // Usando la función deployApp de la shared library
                deployApp(
                    appName: 'mi-proyecto',
                    environment: 'development',
                    deployCommand: 'echo "Simulando despliegue en el servidor de producción"'
                )
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado'
        }
        success {
            // Usando la función notifySlack de la shared library
            notifySlack('Build completado exitosamente!', 'SUCCESS')
        }
        failure {
            // Usando la función notifySlack de la shared library
            notifySlack('Build falló', 'FAILURE')
        }
    }
}